package scalatags
package vdom

import scalatags.generic.Namespace
import scalatags.vdom.raw.VNode
import scalatags.vdom.raw.VirtualDom.VTreeChild

trait SvgTags
    extends generic.SvgTags[Builder, VTreeChild, VTreeChild]
    with TagFactory {
  implicit lazy val svgNamespaceConfig = Namespace.svgNamespaceConfig

  lazy val altGlyph            = nTag("altGlyph")
  lazy val altGlyphDef         = nTag("altGlyphDef")
  lazy val altGlyphItem        = nTag("altGlyphItem")
  lazy val animate             = nTag("animate")
  lazy val animateMotion       = nTag("animateMotion")
  lazy val animateTransform    = nTag("animateTransform")
  lazy val circle              = nTag("circle")
  lazy val clipPath            = nTag("clipPath")
  lazy val `color-profile`     = nTag("color-profile")
  lazy val cursor              = nTag("cursor")
  lazy val defs                = nTag("defs")
  lazy val desc                = nTag("desc")
  lazy val ellipse             = nTag("ellipse")
  lazy val feBlend             = nTag("feBlend")
  lazy val feColorMatrix       = nTag("feColorMatrix")
  lazy val feComponentTransfer = nTag("feComponentTransfer")
  lazy val feComposite         = nTag("feComposite")
  lazy val feConvolveMatrix    = nTag("feConvolveMatrix")
  lazy val feDiffuseLighting   = nTag("feDiffuseLighting")
  lazy val feDisplacementMap   = nTag("feDisplacementMap")
  lazy val feDistantLighting   = nTag("feDistantLighting")
  lazy val feFlood             = nTag("feFlood")
  lazy val feFuncA             = nTag("feFuncA")
  lazy val feFuncB             = nTag("feFuncB")
  lazy val feFuncG             = nTag("feFuncG")
  lazy val feFuncR             = nTag("feFuncR")
  lazy val feGaussianBlur      = nTag("feGaussianBlur")
  lazy val feImage             = nTag("feImage")
  lazy val feMerge             = nTag("feMerge")
  lazy val feMergeNode         = nTag("feMergeNode")
  lazy val feMorphology        = nTag("feMorphology")
  lazy val feOffset            = nTag("feOffset")
  lazy val fePointLight        = nTag("fePointLight")
  lazy val feSpecularLighting  = nTag("feSpecularLighting")
  lazy val feSpotlight         = nTag("feSpotlight")
  lazy val feTile              = nTag("feTile")
  lazy val feTurbulance        = nTag("feTurbulance")
  lazy val filter              = nTag("filter")
  lazy val font                = nTag("font")
  lazy val `font-face`         = nTag("font-face")
  lazy val `font-face-format`  = nTag("font-face-format")
  lazy val `font-face-name`    = nTag("font-face-name")
  lazy val `font-face-src`     = nTag("font-face-src")
  lazy val `font-face-uri`     = nTag("font-face-uri")
  lazy val foreignObject       = nTag("foreignObject")
  lazy val g                   = nTag("g")
  lazy val glyph               = nTag("glyph")
  lazy val glyphRef            = nTag("glyphRef")
  lazy val hkern               = nTag("hkern")
  lazy val image               = nTag("image")
  lazy val line                = nTag("line")
  lazy val linearGradient      = nTag("linearGradient")
  lazy val marker              = nTag("marker")
  lazy val mask                = nTag("mask")
  lazy val metadata            = nTag("metadata")
  lazy val `missing-glyph`     = nTag("missing-glyph")
  lazy val mpath               = nTag("mpath")
  lazy val path                = nTag("path")
  lazy val pattern             = nTag("pattern")
  lazy val polygon             = nTag("polygon")
  lazy val polyline            = nTag("polyline")
  lazy val radialGradient      = nTag("radialGradient")
  lazy val rect                = nTag("rect")
  lazy val set                 = nTag("set")
  lazy val stop                = nTag("stop")
  lazy val svg                 = nTag("svg")
  lazy val switch              = nTag("switch")
  lazy val symbol              = nTag("symbol")
  lazy val text                = nTag("text")
  lazy val textPath            = nTag("textPath")
  lazy val tref                = nTag("tref")
  lazy val tspan               = nTag("tspan")
  lazy val use                 = nTag("use")
  lazy val view                = nTag("view")
  lazy val vkern               = nTag("vkern")

}
